---
- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  tags:
    - skip_ansible_lint

- name: Set systemd version fact
  set_fact:
    nginxlog_exporter_systemd_version: "{{ __systemd_version.stdout_lines[0].split(' ')[-1] }}"

- block:
    - name: Get latest release
      uri:
        url: "https://github.com/martin-helmich/prometheus-nginxlog-exporter/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json
        validate_certs: false
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      no_log: true
      register: _latest_release
      until: _latest_release.status == 200
      retries: 5

    - name: "Set nginxlog_exporter version to {{ _latest_release.json.tag_name[1:] }}"
      set_fact:
        nginxlog_exporter_version: "{{ _latest_release.json.tag_name[1:] }}"
  when: nginxlog_exporter_version == "latest"
  delegate_to: localhost
  run_once: true
